/*
 * Filter Design and Analysis Tool - Generated Filter Coefficients - C Source 
 *  Generated by MATLAB - Signal Processing Toolbox
 */
/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\MATLAB6p5\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate fixed-point
 *   filter coefficients.
 */

/*

Type: hipass

Fstop: 1410 Hz
Fpass: 1500 Hz

Apas: 0.2 dB
Astop: 40 dB

Method: FIR, Equiriple

Fs: 8000 Hz

*/

#define N 171

Int16 h_hi[N] = {
       35,   -192,    -40,     19,     40,     13,    -32,    -43,     -2,
       45,     42,    -13,    -57,    -35,     31,     65,     23,    -51,
      -69,     -4,     71,     65,    -20,    -88,    -54,     48,    100,
       34,    -79,   -104,     -5,    108,     98,    -32,   -133,    -81,
       74,    150,     50,   -119,   -156,     -6,    163,    147,    -49,
     -200,   -120,    113,    227,     73,   -182,   -236,     -7,    251,
      224,    -79,   -312,   -185,    181,    359,    114,   -296,   -384,
       -7,    420,    376,   -139,   -545,   -324,    333,    666,    211,
     -586,   -777,     -8,    931,    870,   -356,  -1463,   -941,   1117,
     2576,    986,  -3934,  -9490,  20845,  -9490,  -3934,    986,   2576,
     1117,   -941,  -1463,   -356,    870,    931,     -8,   -777,   -586,
      211,    666,    333,   -324,   -545,   -139,    376,    420,     -7,
     -384,   -296,    114,    359,    181,   -185,   -312,    -79,    224,
      251,     -7,   -236,   -182,     73,    227,    113,   -120,   -200,
      -49,    147,    163,     -6,   -156,   -119,     50,    150,     74,
      -81,   -133,    -32,     98,    108,     -5,   -104,    -79,     34,
      100,     48,    -54,    -88,    -20,     65,     71,     -4,    -69,
      -51,     23,     65,     31,    -35,    -57,    -13,     42,     45,
       -2,    -43,    -32,     13,     40,     19,    -40,   -192,     35
};
