/*
 * Filter Design and Analysis Tool - Generated Filter Coefficients - C Source 
 *  Generated by MATLAB - Signal Processing Toolbox
 */
/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\MATLAB6p5\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate fixed-point
 *   filter coefficients.
 */

/*

Type: bandpass

Fstop1: 160 Hz
Fpass1: 250 Hz

Fpass2: 1500 Hz
Fstop2: 1590 Hz

Astop1: 40 dB
  Apas: 0.2 dB
Astop2: 40 dB

Method: FIR, Equiriple

Fs: 8000 Hz

*/

#define N 171

Int16 h_mid[N] = {
     -103,     54,   -125,   -124,    -15,     72,     67,      1,    -38,
       -1,     72,     97,     51,      1,     23,    100,    139,     89,
       14,     15,     95,    148,     93,    -16,    -48,     30,    103,
       51,    -87,   -156,    -81,     24,     -5,   -161,   -264,   -187,
      -35,    -15,   -170,   -303,   -226,    -14,     75,    -64,   -231,
     -167,    100,    270,    153,    -67,    -49,    252,    501,    402,
       98,     18,    316,    639,    556,    136,   -101,    155,    560,
      515,    -43,   -496,   -313,    218,    280,   -415,  -1161,  -1080,
     -311,     21,   -803,  -2017,  -2130,   -848,    210,   -751,  -3233,
    -4251,  -1186,   5068,  10206,  10206,   5068,  -1186,  -4251,  -3233,
     -751,    210,   -848,  -2130,  -2017,   -803,     21,   -311,  -1080,
    -1161,   -415,    280,    218,   -313,   -496,    -43,    515,    560,
      155,   -101,    136,    556,    639,    316,     18,     98,    402,
      501,    252,    -49,    -67,    153,    270,    100,   -167,   -231,
      -64,     75,    -14,   -226,   -303,   -170,    -15,    -35,   -187,
     -264,   -161,     -5,     24,    -81,   -156,    -87,     51,    103,
       30,    -48,    -16,     93,    148,     95,     15,     14,     89,
      139,    100,     23,      1,     51,     97,     72,     -1,    -38,
        1,     67,     72,    -15,   -124,   -125,     54,   -103,      0
};
