/*
 * Filter Design and Analysis Tool - Generated Filter Coefficients - C Source 
 *  Generated by MATLAB - Signal Processing Toolbox
 */
 
/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\MATLAB6p5\extern\include\tmwtypes.h 
 */
 
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate fixed-point
 *   filter coefficients.
 */

/*
 * Filtro: FIR (equal ripple)
 * Freq. amostragem: 11025 kHz
 * Especif.: Passa altas
 * Pass band freq.: 500 Hz (0.1 dB)
 * Rej. band freq.: 400 Hz (-50 dB)
 */

const int BL = 269;

const Int16 B[269] = {
       86,    -27,    -25,    -23,    -22,    -22,    -21,    -19,    -17,
      -15,    -11,     -7,     -2,      4,      9,     14,     18,     22,
       24,     24,     23,     20,     16,     10,      3,     -5,    -13,
      -21,    -28,    -33,    -36,    -37,    -36,    -32,    -25,    -16,
       -6,      5,     17,     29,     39,     47,     52,     54,     52,
       47,     38,     26,     11,     -5,    -22,    -38,    -53,    -64,
      -72,    -76,    -74,    -67,    -56,    -39,    -19,      3,     27,
       49,     70,     87,    100,    105,    104,     96,     81,     59,
       32,      2,    -31,    -63,    -93,   -118,   -136,   -146,   -147,
     -137,   -118,    -89,    -53,    -10,     35,     81,    124,    161,
      190,    207,    211,    201,    176,    137,     87,     27,    -39,
     -106,   -172,   -230,   -277,   -308,   -320,   -311,   -280,   -227,
     -153,    -62,     41,    152,    263,    367,    456,    524,    562,
      566,    530,    452,    329,    163,    -43,   -284,   -554,   -844,
    -1144,  -1444,  -1733,  -1999,  -2233,  -2426,  -2569,  -2657,  30081,
    -2657,  -2569,  -2426,  -2233,  -1999,  -1733,  -1444,  -1144,   -844,
     -554,   -284,    -43,    163,    329,    452,    530,    566,    562,
      524,    456,    367,    263,    152,     41,    -62,   -153,   -227,
     -280,   -311,   -320,   -308,   -277,   -230,   -172,   -106,    -39,
       27,     87,    137,    176,    201,    211,    207,    190,    161,
      124,     81,     35,    -10,    -53,    -89,   -118,   -137,   -147,
     -146,   -136,   -118,    -93,    -63,    -31,      2,     32,     59,
       81,     96,    104,    105,    100,     87,     70,     49,     27,
        3,    -19,    -39,    -56,    -67,    -74,    -76,    -72,    -64,
      -53,    -38,    -22,     -5,     11,     26,     38,     47,     52,
       54,     52,     47,     39,     29,     17,      5,     -6,    -16,
      -25,    -32,    -36,    -37,    -36,    -33,    -28,    -21,    -13,
       -5,      3,     10,     16,     20,     23,     24,     24,     22,
       18,     14,      9,      4,     -2,     -7,    -11,    -15,    -17,
      -19,    -21,    -22,    -22,    -23,    -25,    -27,     86
};
