/*
 * Filter Design and Analysis Tool - Generated Filter Coefficients - C Source 
 *  Generated by MATLAB - Signal Processing Toolbox
 */
/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\MATLAB6p5\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate fixed-point
 *   filter coefficients.
 */
 
/*
 * Filtro: FIR (equal ripple)
 * Freq. amostragem: 8000 kHz
 * Especif.: Passa baixas
 * Rej. band freq.: 500 Hz (-50 dB)
 * Pass band freq.: 400 Hz (1 dB)
 */
 
#define N 46
Int16 h[N] = {
      -60,     48,    114,    213,    328,    429,    486,    465,    345,
      124,   -174,   -500,   -780,   -931,   -877,   -563,     27,    861,
     1857,   2900,   3850,   4574,   4965,   4965,   4574,   3850,   2900,
     1857,    861,     27,   -563,   -877,   -931,   -780,   -500,   -174,
      124,    345,    465,    486,    429,    328,    213,    114,     48,
      -60
};
