/*
 * Filter Design and Analysis Tool - Generated Filter Coefficients - C Source 
 *  Generated by MATLAB - Signal Processing Toolbox
 */
/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\MATLAB6p5\extern\include\tmwtypes.h 
 */
 
#define NSEC 4

Int16 Blen[NSEC] = { 2,3,3,3 };
Int16 B[NSEC][3] = {
  {
    32767, -32768,      0 
  },
  {
    32767, -32768,  32767 
  },
  {
    32767, -32768,  32767 
  },
  {
    32767, -32768,  32767 
  }
};

Int16 Alen[NSEC] = { 2,3,3,3 };
Int16 A[NSEC][3] = {
  {
    32767, -14759,      0 
  },
  {
    32767, -32768,  19418 
  },
  {
    32767, -32768,  28596 
  },
  {
    32767, -32768,  31823 
  }
};
