/*
 * Filter Design and Analysis Tool - Generated Filter Coefficients - C Source 
 *  Generated by MATLAB - Signal Processing Toolbox
 */
/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\MATLAB6p5\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate fixed-point
 *   filter coefficients.
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,2,3,3,3 };
const int16_T NUM[MWSPT_NSEC][3] = {
  {
    28713,      0,      0 
  },
  {
    32767, -32768,      0 
  },
  {
    32767, -32768,  32767 
  },
  {
    32767, -32768,  32767 
  },
  {
    32767, -32768,  32767 
  }
};
const int DL[MWSPT_NSEC] = { 1,2,3,3,3 };
const int16_T DEN[MWSPT_NSEC][3] = {
  {
    32767,      0,      0 
  },
  {
    32767, -28602,      0 
  },
  {
    32767, -32768,  29702 
  },
  {
    32767, -32768,  31946 
  },
  {
    32767, -32768,  32590 
  }
};
