/*
 * Filter Design and Analysis Tool - Generated Filter Coefficients - C Source 
 *  Generated by MATLAB - Signal Processing Toolbox
 */
/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\MATLAB6p5\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate fixed-point
 *   filter coefficients.
 */

/*

Type: lowpass

Fpass: 250 Hz
Fstop: 340 Hz

Apas: 0.2 dB
Astop: 40 dB

Method: FIR, Equiriple

Fs: 8000 Hz

*/

#define BL = 170;

Int16 B[170] = {
      178,    -18,    -21,    -25,    -31,    -38,    -45,    -51,    -57,
      -61,    -62,    -61,    -58,    -51,    -41,    -29,    -14,      3,
       20,     38,     54,     69,     80,     88,     91,     90,     82,
       70,     52,     30,      5,    -23,    -52,    -80,   -105,   -127,
     -143,   -153,   -154,   -147,   -131,   -106,    -73,    -34,     10,
       58,    106,    151,    192,    225,    249,    260,    257,    239,
      207,    160,     99,     27,    -53,   -138,   -223,   -305,   -377,
     -436,   -476,   -494,   -486,   -448,   -380,   -279,   -148,     13,
      201,    411,    638,    876,   1120,   1360,   1591,   1804,   1994,
     2154,   2279,   2365,   2408,   2408,   2365,   2279,   2154,   1994,
     1804,   1591,   1360,   1120,    876,    638,    411,    201,     13,
     -148,   -279,   -380,   -448,   -486,   -494,   -476,   -436,   -377,
     -305,   -223,   -138,    -53,     27,     99,    160,    207,    239,
      257,    260,    249,    225,    192,    151,    106,     58,     10,
      -34,    -73,   -106,   -131,   -147,   -154,   -153,   -143,   -127,
     -105,    -80,    -52,    -23,      5,     30,     52,     70,     82,
       90,     91,     88,     80,     69,     54,     38,     20,      3,
      -14,    -29,    -41,    -51,    -58,    -61,    -62,    -61,    -57,
      -51,    -45,    -38,    -31,    -25,    -21,    -18,    178
};
